baseurl = "http://yuri.is/"
relativeURLs = true
languageCode = "en-us"
title = "Yuri Vishnevsky"
theme = "minimal"
builddrafts = true

[blackfriday]
latexDashes = false
plainIDAnchors = true
sourceRelativeLinksEval = true
