baseurl = "http://yuri.is/"
relativeURLs = true
languageCode = "en-us"
title = "Yuri Vishnevsky"
theme = "minimal"

[blackfriday]
latexDashes = false
plainIDAnchors = false
sourceRelativeLinksEval = true
